### ISSUE TITLE
Change Entity

### ISSUE THREAD

**Issue by ElectroGamesDev** [refteams/libNpcDialogue#1]
Hello. How do I change the Entity in the dialog?

**Comment by ElectroGamesDev** [comment]
Buttons also don't do anything when pressed

**Comment by alvin0319** [comment]
@ElectroGamesYT You have to set the click handler before sending dialogue.

**Comment by ElectroGamesDev** [comment]
What do you mean?
I did exactly what you did in the DialogueTest.php

**Comment by alvin0319** [comment]
@ElectroGamesYT I have no idea what are you talking about. did you registered your plugin using 
```php
if(!libNpcDialogue::isRegistered()) libNpcDialogue::register($this);
```
on your plugin in onEnable()?

**Comment by ElectroGamesYT** [comment]
> @ElectroGamesYT I have no idea what are you talking about. did you registered your plugin using
> 
> ```
> if(!libNpcDialogue::isRegistered()) libNpcDialogue::register($this);
> ```
> 
> on your plugin in onEnable()?

Yes... If it wasn't, the Dialog wouldnt even open up lol.

**Comment by ElectroGamesYT** [comment]
Please update your API example if something is incorrect since thats what I used.

**Comment by ElectroGamesDev** [comment]
> @ElectroGamesYT I have no idea what are you talking about. did you registered your plugin using
> 
> ```
> if(!libNpcDialogue::isRegistered()) libNpcDialogue::register($this);
> ```
> 
> on your plugin in onEnable()?

I guess this fixed it.. the Dialog was popping up so I thought this was useless but thanks.

**Comment by alvin0319** [comment]
In creative mode, you will see the dialogue edit screen. but for now they are useless since I didn't implemente them.
