### ISSUE TITLE
Broken error

### ISSUE THREAD

**Issue by Astro-PM** [refteams/libNpcDialogue#11]
![Screenshot_2023-05-06-12-52-00-103_com android chrome](https://user-images.githubusercontent.com/129596573/236609650-b46dbbf9-1b7f-4ca1-8c17-7131dee53c5a.jpg)
![Screenshot_2023-05-06-12-51-55-157_com android chrome](https://user-images.githubusercontent.com/129596573/236609653-aeb1a5c1-79e6-4cb9-876e-19bb9eccb5ae.jpg)

**Comment by alvin0319** [comment]
Can you give us more details? The screenshot you gave is not readable.
