### ISSUE TITLE
Error with libNpcDialogue_dev-2.phar

### ISSUE THREAD

**Issue by galaxytwenty** [refteams/libNpcDialogue#8]
[Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\protocol\AddActorPacket::create(): Argument #9 ($bodyYaw) must be of type float, array given, called in phar://C:/Users/******/Desktop/FAIL SERVER/test/virions/libNpcDialogue_dev-2.phar/src/ref/libNpcDialogue/NpcDialogue.php on line 105" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AddActorPacket" at line 56

can u update this lib ?

**Comment by alvin0319** [comment]
Have you tried with the latest commit, I don't get that error when using the latest commit of the virion.

**Comment by galaxytwenty** [comment]
have try the dev-2 and directly download from GH

**Comment by alvin0319** [comment]
What version of PocketMine-MP do you use?

**Comment by galaxytwenty** [comment]
Server version: 4.17.2 (git hash: 9e8c0a6beabf1fac7c81b1f9687ed998a630a5ca)

**Comment by galaxytwenty** [comment]
i try to Update now my PM version

**Comment by galaxytwenty** [comment]
same with: Server version: 4.18.4 (git hash: f61f72180f2498648875ea7947e297b485fefccc)

too when i run without other plugins

**Comment by galaxytwenty** [comment]
![issue npclib](https://user-images.githubusercontent.com/79281788/231214413-a0535e97-80e4-4aca-8dd6-7ee25f43d818.png)

That was my IDE says

**Comment by galaxytwenty** [comment]
have made a PR that fix the error

**Comment by galaxytwenty** [comment]
One last question, can i set the Skin that displayed in the window ?
